services:
  mongodb:
    image: mongo:latest
    container_name: taverna_db
    hostname: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - taverna-network

  mongo-init:
    image: mongo:latest
    container_name: taverna_mongo_init
    networks:
      - taverna-network
    depends_on:
      mongodb:
        condition: service_healthy
    entrypoint: >
      bash -c "
      echo 'Aguardando o MongoDB...' ;
      until mongosh --host mongodb:27017 --eval 'db.runCommand({ping:1})' &>/dev/null; do sleep 2; done;
      mongosh --host mongodb:27017 --eval 'try { rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongodb:27017\"}]}); } catch(e) {}'
      "

  database-seed:
    build: ./backend
    container_name: taverna_seed
    networks:
      - taverna-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/taverna?replicaSet=rs0&directConnection=true
    depends_on:
      mongodb:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully
    entrypoint: ["npx", "tsx", "src/scripts/seed-master.ts"]

  api:
    build: ./backend
    container_name: taverna_api
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-secret_fallback}
      - MONGO_URI=mongodb://mongodb:27017/taverna?replicaSet=rs0&directConnection=true
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
    depends_on:
      mongodb:
        condition: service_healthy
      database-seed:
        condition: service_completed_successfully
    networks:
      - taverna-network

  web:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:3333/api/v1
    container_name: taverna_web
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3333/api/v1
    depends_on:
      - api
    networks:
      - taverna-network

networks:
  taverna-network:
    driver: bridge
