version: "3.8"

services:
  # --- BANCO DE DADOS (Persistência com Auto-Cura) ---
  mongodb:
    image: mongo:latest
    container_name: taverna_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS:-admin}
    volumes:
      - mongo-data:/data/db
    networks:
      - taverna-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- BACKEND (API Fastify) ---
  api:
    build: ./backend
    container_name: taverna_api
    restart: unless-stopped
    ports:
      - "3334:3333" # Acessível no seu navegador via localhost:3334
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0 # <--- Força o Fastify a ouvir conexões externas
      - PORT=3333
      - MONGO_URI=mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-admin}@mongodb:27017/taverna?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - taverna-network

  # --- FRONTEND (Interface React + Nginx) ---
  frontend:
    build: ./frontend
    container_name: taverna_web
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3334/api/v1
    depends_on:
      - api
    networks:
      - taverna-network

# --- INFRAESTRUTURA DE REDE E VOLUMES ---
networks:
  taverna-network:
    driver: bridge

volumes:
  mongo-data:
