services:
  mongodb:
    image: mongo:latest
    container_name: taverna_db
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - taverna-network

  mongo-init:
    image: mongo:latest
    container_name: taverna_mongo_init
    networks:
      - taverna-network
    depends_on:
      mongodb:
        condition: service_healthy
    entrypoint: >
      bash -c "
      echo 'Aguardando o MongoDB estabilizar...' ;
      until mongosh --host mongodb:27017 --eval 'db.runCommand({ping:1})' &>/dev/null; do
        sleep 2;
      done;
      echo 'MongoDB pronto! Verificando Replica Set...' ;
      mongosh --host mongodb:27017 --eval '
        try {
          if (!rs.status().ok) {
            rs.initiate({
              _id: \"rs0\",
              members: [{ _id: 0, host: \"mongodb:27017\" }]
            });
            console.log(\"Replica Set inicializado com sucesso!\");
          } else {
            console.log(\"Replica Set j√° estava ativo.\");
          }
        } catch (e) {
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"mongodb:27017\" }]
          });
        }
      '
      "

  database-seed:
    build: ./backend
    container_name: taverna_seed
    networks:
      - taverna-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/taverna?replicaSet=rs0&directConnection=true
    depends_on:
      mongodb:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully
    # Usa npx tsx para rodar o script TS ignorando erros de loader do Node 22
    entrypoint: ["npx", "tsx", "src/scripts/seed-master.ts"]

  api:
    build: ./backend
    container_name: taverna_api
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=mongodb://mongodb:27017/taverna?replicaSet=rs0&directConnection=true
      - CORS_ORIGIN=http://localhost:8080
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
      - MELHOR_ENVIO_TOKEN=${MELHOR_ENVIO_TOKEN}
      - CEP_ORIGEM=${CEP_ORIGEM}
    depends_on:
      mongodb:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully
      database-seed:
        condition: service_completed_successfully
    networks:
      - taverna-network

  web:
    build: ./frontend
    container_name: taverna_web
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3333/api/v1
    depends_on:
      - api
    networks:
      - taverna-network

networks:
  taverna-network:
    driver: bridge
